export const MEILISEARCH_HOST = process.env.NEXT_PUBLIC_MEILISEARCH_HOST
export const MEILISEARCH_API_KEY = process.env.NEXT_PUBLIC_MEILISEARCH_API_KEY

export const DEFAULT_SEMANTIC_RATIO = 0.5
export const DEFAULT_EMBEDDER =
  process.env.NEXT_PUBLIC_MEILISEARCH_EMBEDDER ?? 'default'

console.log('MEILISEARCH_HOST', MEILISEARCH_HOST)
console.log('MEILISEARCH_API_KEY', MEILISEARCH_API_KEY)
